### Buscar todos os carros
GET http://localhost:8080/api/v1/grades

### Buscar carro pelo ID

GET http://localhost:8080/api/v1/grades/1

### Inserir uma nova Matéria
POST http://localhost:8080/api/v1/grades
Content-Type: application/json

{
  "curso": "Engenharia de Software", 
  "semestres": [
    {
      "nome": "2",
      "disciplinas": [
        {
          "nome": "Estrutura 2",
          "cargaHoraria": 72
        },
        {
          "nome": "Redes",
          "cargaHoraria": 72
        }
      ]
    },
    {
      "nome": "2",
      "disciplinas": [
        {
          "nome": "TAPR1",
          "cargaHoraria": 72
        },
        {
          "nome": "DAS3",
          "cargaHoraria": 72
        }
      ]
    }
  ]
}

### Atualizar a Matéria
PUT http://localhost:8080/api/v1/grades/80b65866-602f-4325-ac59-5be26939f51a
Content-Type: application/json

{
  "curso": "Engenharia de Software", 
  "semestres": [
    {
      "nome": "1",
      "disciplinas": [
        {
          "nome": "Das",
          "cargaHoraria": 72
        },
        {
          "nome": "Estrutura de Dados",
          "cargaHoraria": 72
        }
      ]
    },
    {
      "nome": "2",
      "disciplinas": [
        {
          "nome": "TAPR",
          "cargaHoraria": 72
        },
        {
          "nome": "DAS2",
          "cargaHoraria": 72
        }
      ]
    }
  ]
}


### Remover a Matéria
DELETE  http://localhost:8080/api/v1/grades/866588b4-2a1b-4e0c-a42b-31a8a897a774
Content-Type: application/json